# Generated by Django 4.2 on 2024-02-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=1000)),
                ('country_code', models.CharField(max_length=1000)),
                ('coordinate', models.CharField(max_length=1000)),
                ('temp', models.CharField(max_length=1000)),
                ('pressure', models.CharField(max_length=1000)),
                ('humidity', models.CharField(max_length=1000)),
            ],
        ),
    ]
